title: Poyoncio | Reversing & fun
baseurl: ""

date_format: "%Y-%m-%d"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave someone empty to disable it
google_analytics: UA-89488195-1
disqus_shortname:
